### ISSUE TITLE
New Brigade Sign Up Form Process

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#311]
We've got a plan for the new Brigade sign up form. It will be an embeddable form (much like the [civic issues embed](http://www.codeforamerica.org/geeks/civicissues/embed)) that has optional styling, and integration with mailchimp and our peopledb.

The flow will be:
1. Someone signs up
2. The form optionally posts to Mailchimp
3. The form also posts to our [PeopleDB](https://people.codeforamerica.org/brigade/)

Our internal process will be:
1. We set up Mailchimp auto response emails
2. We test out some welcome to the Brigade email series with the marketing and content teams.
3. We start some analytics on our list of Brigade people in the peopledb

A Brigade Captain's process will be:
1. They go to `/brigade/signup/form`
2. They use the form to build their own sign up form. They enter their mailchimp list url and their Brigade CfAPI id (`Code-for-San-Francisco`)
3. They embed it on their own site.
4. New people get put on their Mailchimp
5. They can also access people from our PeopleDB. It will have additional data in it, such as attendance and a growing list of other info.

#### TASKS
- [x] Talk to communities team about using Mailchimp for follow ups
- [x] Talk to Brigades about what they use for email signups.
- [x] Build the sign up form
- [x] Build the individual Brigade sign up form
- [ ] Build the form builder
- [ ] User testing the form, user test the embed form

**Comment by ondrae** [comment]
On the main page, use the universal sign up. On the individual Brigade pages, use our special form.

**Comment by ondrae** [comment]
I ended up undoing most of this. We instead are just using the universal signup form, then overwriting it where needed with javascript. The signup form builder for Brigades to use on their own site is still a separate issue.
