### ISSUE TITLE
Build a signup form builder

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#313]
#### Description

In #311 we are building a brand new sign up form. One of the goals for this form is that it should be embeddable in any individual Brigade's site. The form then posts both to that Brigade's mailchimp list and to our PeopleDB.

We need the form builder to help them input their Mailchimp list id and their CfAPI Brigade ID.
#### Tasks
- [ ] Build a form builder at `/brigade/signup/form`
- [ ] Write very clear instructions for how to find the Mailchimp list id.
- [ ] Have a drop down to choose your Brigade id.
- [ ] Show the html to embed.

**Comment by ondrae** [comment]
Hey @davidrleonard how did you get the `https://codeforamerica.us2.list-manage.com/subscribe/post-json?u=d9acf2a4c694efbd76a48936f&amp;id=3ac3aef1a5` url for the main "Email List" from mailchimp.

When I go to their embeddable forms, I only see `..subscribe/post?u=d9acf2a4c6...` without the -json

**Comment by ondrae** [comment]
Do we need to include javascript with this too? To handle the response, or keep the user on the site?

**Comment by ondrae** [comment]
Updated language from @ZoeBlumenfeld for the embedded Brigade signup forms.
"Get updates from Code for America and information about events from your local Brigade."
