### ISSUE TITLE
Add /checkin tool

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#344]
#### Description
We are working on systems to help track attendance for our volunteer Brigades. We've got a secure database where we will store these checkins. We need to build a front end for this check in tool. This tool will need to post some data with a likely schema of `name, email, date, organization_cfapi_url, event, question, answer`.

#### Scenarios
Talking to the Brigades, there are a few different ways they track attendance.
* At the beginning, they ask everyone to go to a short url to check in.
* They have a security guard or laptop at the entrance, where they collect attendance.
* They pass around an attendance sheet during the meeting.
* A volunteer manually counts people

Some groups use Meetup and want people to check in there. Some use Excel to record attendance.

Some groups like to include a question with their check in. What skills do you have? What do you want to work on? How did you hear about us?

#### Existing
We had built a mock up a while ago at http://codeforamerica.github.io/attendance/. It currently posts to GDocs. What is nice about this mock up, is that it doesn't forget your event name or Brigade name as people enter the info. It works in the scenarios above.

#### Files
A natural place for this tool to live is on the Brigade website, where we generate a unique page for each Brigade. http://www.codeforamerica.org/brigade/Code-for-San-Francisco/checkin New routes needed in `app.py` and a new template for the check in page.

#### Security
We can either require a secret key to be able to post attendance or not. By building the check in tool to our Brigade site, we have control. If we didn't require a secret key, the only risk is spammed attendance, which we should take as a compliment.

#### Tasks
- [x] Finish all the PeopleDB back end work
- [x] Build a mock check in tool that posts to the peopledb
- [x] Try out the mvp with Code for San Francisco
- [x] Write tesssssssts
- [x] Build tool in to the Brigade site for all Brigades
- [ ] Roll out

**Comment by ondrae** [comment]
@jmadans has a connection to an SMS service that could be used too

**Comment by ondrae** [comment]
Got a suggestion of another version of the checkin tool. It would work to the "A volunteer manually counts people". Have a list of people that can be checked off. Or have a search for names, so an event leader can checkin other people.

Also got a request to add bulk attendance, like "50 people attended tonight". Not sure how to do that one.

**Comment by migurski** [comment]
`/checkin` could take an array of people.

**Comment by eunicekokor** [comment]
Are we still thinking about adding a 'bulk add' option to /checkin or adding any of these other versions of the checkin tool? 

Also how should the views for /checkin and /brigade-id/checkin differ? I was thinking of a couple versions/additions that might help speed up the brigade check in process

**Comment by ondrae** [comment]
We'll definitely do iterations based on what the Brigades respond with. Lets stick with the most minimal version we can for now.

**Comment by ondrae** [comment]
Lots of support for the different styles of checkin listed up top. Also, a request to just add a raw number of checkins, with no names and emails attached.

**Comment by ondrae** [comment]
A suggestion for hardware! Badge printers! RFID tags!

**Comment by migurski** [comment]
Cool!

**Comment by ondrae** [comment]
An update. I think `/brigade/checkin` should be the main place where all other attendance tools POST to.

The  schema that `/brigade/checkin` should expect is:
```
[
  {
    name : "Margaret Hamilton",
    email : "apollo@nasa.gov",
    event : "Moon Landing", 
    cfapi_url : "https://www.codeforamerica.org/api/organizations/Kennedy-Space-Center",
    extras : {
      "question" : "What did you do today?",
      "answer" : "Launched a rocket to the moon. Invented software engineering."
     }
   },
  ...
] 
```
* It should expect a list of checkins.
* All of the attributes are optional except for `cfapi_url`.
* We haven't explored the `extras` attribute too much, yet I think we want it to accept any random json.

A GET request to `brigade/checkin` will still show a checkin form, which would post to itself.

Once receiving a POST, `/brigade/checkin` will post to our PeopleDB with a secure key attached. This will let us have one consistent endpoint, no matter what we end up doing with the database.

**Comment by migurski** [comment]
Can I recommend that `/brigade/checkin` should accept [x-www-form-urlencoded POST data](http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1), rather than JSON? Browsers can make it without Javascript.

**Comment by ondrae** [comment]
I was worried about that. I was over engineering a little to support the "50 people attended" type of checkin rather than 50 individual checkins.

**Comment by migurski** [comment]
I think it’s still possible to support multiple checkins. It’s not a native Flask thing I’m aware of, but PHP [supports complex arrays in POST data](http://bbrown.kennesaw.edu/papers/php2.html). Seems like a thing that someone might have copied, or we could.

**Comment by eunicekokor** [comment]
If after receiving a POST, The form response is an [ImmutableMultiDict](http://werkzeug.pocoo.org/docs/0.10/datastructures/#werkzeug.datastructures.MultiDict) object like below.

```
ImmutableMultiDict([('email', u'you@example.com'), ('cfapi_url', u'https://www.codeforamerica.org/api/organizations/Hack-for-LA'), ('event', u'Civic Hack Night'), ('name', u'Civic Hacker')])
```
Not sure how to actually implement it to allow for a list of checkins, but everything else should work fine! All my updates are on the branch!

**Comment by ondrae** [comment]
:rocket: :guitar:

**Comment by ondrae** [comment]
We'll merge and deploy in the morning.

A few notes:
* The call to get the `organizations.geojson` only needs to happen if `brigadeid` is `None`.
* I like how you've saved the org name and event name between requests
* We'll need to do a little clean up on the extras part.

**Comment by kareemadesola** [comment]
> #### Description
> We are working on systems to help track attendance for our volunteer Brigades. We've got a secure database where we will store these checkins. We need to build a front end for this check in tool. This tool will need to post some data with a likely schema of `name, email, date, organization_cfapi_url, event, question, answer`.
> 
> #### Scenarios
> Talking to the Brigades, there are a few different ways they track attendance.
> 
> * At the beginning, they ask everyone to go to a short url to check in.
> * They have a security guard or laptop at the entrance, where they collect attendance.
> * They pass around an attendance sheet during the meeting.
> * A volunteer manually counts people
> 
> Some groups use Meetup and want people to check in there. Some use Excel to record attendance.
> 
> Some groups like to include a question with their check in. What skills do you have? What do you want to work on? How did you hear about us?
> 
> #### Existing
> We had built a mock up a while ago at http://codeforamerica.github.io/attendance/. It currently posts to GDocs. What is nice about this mock up, is that it doesn't forget your event name or Brigade name as people enter the info. It works in the scenarios above.
> 
> #### Files
> A natural place for this tool to live is on the Brigade website, where we generate a unique page for each Brigade. http://www.codeforamerica.org/brigade/Code-for-San-Francisco/checkin New routes needed in `app.py` and a new template for the check in page.
> 
> #### Security
> We can either require a secret key to be able to post attendance or not. By building the check in tool to our Brigade site, we have control. If we didn't require a secret key, the only risk is spammed attendance, which we should take as a compliment.
> 
> #### Tasks
> * [x]  Finish all the PeopleDB back end work
> * [x]  Build a mock check in tool that posts to the peopledb
> * [x]  Try out the mvp with Code for San Francisco
> * [x]  Write tesssssssts
> * [x]  Build tool in to the Brigade site for all Brigades
> * [x]  Roll out

This issue has really nice content and quality

**Comment by kareemadesola** [comment]
Really nice content

**Comment by kareemadesola** [comment]
Duplicate of #344
