### ISSUE TITLE
Add an /analytics view

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#345]
#### Description

We have a master list of civic tech projects with the cfapi. We should work to get a master list of analytics data for those projects.

Just idly brainstorming with @MatthewLoveless here are our first thoughts.

Give each Brigade a Google Analytics javascript snippet that includes the Brigade name and project name. Have them all post to the same GA account though.

We'd get pageviews and visitors info for all civic tech projects. We could also break it down by Brigade using the GA api, to create some nice analytics sites that could live at codeforamerica.org/brigade/Code-for-San-Francisco/analytics. Imagine each Brigade getting something like http://analytics.phila.gov/ for free. You could even break it down by each project pretty easily. 
#### Research

We should talk to the Brigades and see what they do now for:
- individual project analytics
- Brigade total analytics
- tools do they like and are comfortable with
#### Snippet Builder

We'll need to make a form to generate the GA javascript snippet. It will need to add the Brigades name to each pageview. Perhaps add the project name too? Maybe we get that from the url.
An example of this type of form is at http://www.codeforamerica.org/geeks/civicissues/embed
#### Analytics view
- Civic Tech Movement Analytics
  http://www.codeforamerica.org/brigade/analytics
  Shows the page views and demographics of the whole civic tech movement.
- Brigade analytics
  http://www.codeforamerica.org/brigade/Code-for-San-Francisco/analytics
  Shows the analytics for an individual Brigade
- Project Analytics
  http://www.codeforamerica.org/brigade/Code-for-San-Francisco/projects/SF-In-Progress/analytics
  Show the analytics for an individual project?
#### Tasks
- [ ] Research with the Brigades
- [ ] Build a mvp of the individual Brigade view
- [ ] Try it out with a few Brigades
- [ ] Write tests
- [ ] Build a full version into the Brigade site that works for all Brigades.
- [ ] Include it in the CfAPI for others to build on ????
- [ ] Require usage of the snippet to get future CfA funding.

**Comment by tdooner** [comment]
Thanks for documenting the thought behind this idea, but I'm going to close this issue and we can refer back to this if we revisit this idea.
