### ISSUE TITLE
Respond to a checkin with a JSON success message

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#361]
#### Description
Right now, a response to a successful checkin is a 200 and our html form for another checkin. This isnt helpful for groups who are building their own checkin tools https://github.com/codeforamerica/brigade/issues/352.

We should change the response to be a json success message. I'm not sure how to handle reloading the checkin form on our site though. We still want to redirect people using our form ...

We use a redirect here https://github.com/codeforamerica/brigade/blob/master/app.py#L526 instead of a response with json. We should use something like:
```
{
  "message" : "success"
}
```

#### Files
app.py, templates/checkin.html

#### Tasks
- [ ] Change the response for a successful checkin
- [ ] Edit the tests
- [ ] Figure out to redirect people using our form
