### ISSUE TITLE
Write a guide for our attendance tools

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#387]
#### Description
We need something written down about the importance of attendance data for organizing a group.

We think its important for:
* fundraising
* attracting new people
* retaining former members
* recognizing current members

#### Tasks
- [ ] Finish our user research about the tools
- [ ] Do a little academic research
- [ ] Write a guide for how to use the tools
- [ ] Write a guide for why to use the tools
