### ISSUE TITLE
Project Search Analytics

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#401]
#### Description
We need a good way to know what how people are using the project search tool and what they are searching for. The two ways to do this are through analytics or logging. We don't have a good logging infrastructure built, so analytics will be much easier. We're hoping Google Analytics will be able to do what we want.

#### Tasks
- [x] Add GAnalytics to the search page
- [ ] Can GAnalytics detect and report on url parameters?
- [x] Do we need to pass in special attributes for GAnalytics on the search page?
