### ISSUE TITLE
Manually Tag Projects

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#403]
#### Description
Once the civic json builder is ready, we should try it out. Lets use it to go through the a big list of projects and add appropriate stages and tags.

The projects list:
* Code for America projects
* Chris' focus area projects list
* The top three pages of most recently updated projects

#### What we want to learn 
* What technical improvements to make to the tool?
* What process improvements to make to the guide on how to use?
* Is a civic json builder even worth it? Should we recommend to make by hand instead?
* Are [the stages](http://www.codeforamerica.org/brigade/projects/stages) appropriate and easy to understand?
* Do tags need some kind of structure?
* Should we allow other statuses?

There will also be a bunch of lessons we'll start to learn about the Project Search tool, yet those will be gathered and acted on in a later sprint.

#### Tasks
- [x] Finish #390 
- [x] Figure out way to link to civic json builder
- [x] @ondrae will schedule a time to do this together with @tmaybe and @GovInTrenches 
- [x] Do the civic json building for a bunch of projects
- [x] Collect lessons and improvements
