### ISSUE TITLE
Project Search Roll Out

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#407]
#### Description
Lets do an official roll out

#### tasks
- [ ] Schedule a roll out plan
- [ ] Create a demo video
- [ ] Add video to Captain's orientation
